# Generated by Django 3.2.9 on 2021-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('owner_id', models.CharField(max_length=10)),
                ('like_num', models.IntegerField(default=0)),
                ('favorite_num', models.IntegerField(default=0)),
                ('topic_text', models.CharField(max_length=20)),
                ('content_text', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('r_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('owner_id', models.CharField(max_length=10)),
                ('post_id', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
            ],
        ),
    ]
