# Generated by Django 3.2.9 on 2021-11-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='response_num',
            field=models.IntegerField(default=0),
        ),
    ]
