# Generated by Django 3.2.9 on 2021-11-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20211126_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='use_favoritesNum',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_likeNum',
        ),
    ]
