# Generated by Django 3.2.9 on 2021-11-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20211126_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='topic_text',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='topic_text',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
