# Generated by Django 3.2.9 on 2021-12-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_post_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
