# Generated by Django 3.2.9 on 2021-12-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20211202_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinterest',
            old_name='count',
            new_name='term_count',
        ),
    ]
